## Question 3

In [1]:
import nltk
from nltk.tokenize import sent_tokenize

In [2]:
corpus = ["New York City’s public transportation network is slashing service by at least 25 percent with ridership in free fall and an increasing number of sick workers hobbling its ability to run normally. The decision to cut service on the nation’s largest transportation network on Tuesday came after ridership on the subway plunged a staggering 87 percent — or nearly 4.8 million riders — compared with the same day last year and personnel shortages forced the Metropolitan Transportation Authority, which oversees subways, buses and two commuter rails, to temporarily eliminate service on three subway lines: the B, the W and the Z.New York City’s transportation system typically carries eight million riders each weekday. But the sudden and steep drops in ridership have severely strained the authority’s operating budget, about half of which comes from fares and tolls."]

In [3]:
sentences = sent_tokenize(''.join(corpus)) 

## Question 4

In [4]:
from sklearn.feature_extraction.text import CountVectorizer

In [5]:
cv = CountVectorizer(min_df=0., max_df=1.)
cv_matrix = cv.fit_transform(sentences)

## Question 5

In [6]:
from sklearn.metrics.pairwise import cosine_similarity

In [7]:
sentences = sent_tokenize(''.join(corpus))
cv = CountVectorizer()

In [8]:
x = cv.fit_transform(sentences)

In [23]:
m,n = x.shape

for i in range(m):
    cs = cosine_similarity(x[i], x)
    print(cs)

[[1.         0.23466699 0.16703828]]
[[0.23466699 1.         0.36892584]]
[[0.16703828 0.36892584 1.        ]]


In [43]:
corpus_12 = [sentences[0],sentences[1]]
corpus_13 = [sentences[0],sentences[2]]
corpus_23 = [sentences[1],sentences[2]]

In [49]:
matrix12 = tfv.fit_transform(corpus_12)
matrix13 = tfv.fit_transform(corpus_13)
matrix23 = tfv.fit_transform(corpus_23)

In [50]:
cosine_similarity(matrix12[0:1],matrix12)

array([[1.        , 0.13738035]])

In [51]:
cosine_similarity(matrix13[0:1],matrix13)

array([[1.        , 0.09324347]])

In [52]:
cosine_similarity(matrix23[0:1],matrix23)

array([[1.        , 0.23688917]])

## Question 6

In [10]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.decomposition import LatentDirichletAllocation

In [33]:
lda_model = LatentDirichletAllocation(n_components = 5, max_iter=500, max_doc_update_iter=50,               
                      learning_method='online', batch_size=1740,
                      learning_offset=50, random_state=42,
                      n_jobs=16)

In [34]:
tfv = TfidfVectorizer()
vectorized_model = tfv.fit_transform(corpus)

In [35]:
topics = lda_model.fit_transform(vectorized_model)
components = lda_model.components_
terms = tfv.get_feature_names_out()

In [36]:
for index, component in enumerate(components):
    zipped = zip(terms, component)
    keys = sorted(zipped, key = lambda t: t[1], reverse=True)
    word_list =list(dict(keys).keys())
    print("Topic "+str(index)+": ",word_list)

Topic 0:  ['staggering', 'after', 'nearly', 'by', 'sudden', 'lines', 'free', 'increasing', 'operating', 'day', 'typically', 'least', 'year', 'an', 'subways', 'eight', 'hobbling', 'at', '25', 'same', 'metropolitan', 'number', 'or', 'from', 'but', 'public', 'strained', 'rails', 'workers', 'each', 'eliminate', 'oversees', 'slashing', 'compared', 'sick', 'nation', 'subway', 'severely', 'fall', '87', 'run', 'steep', 'last', 'in', 'normally', 'came', 'ability', 'about', 'percent', 'commuter', 'fares', 'its', 'two', 'plunged', 'half', 'forced', 'largest', 'carries', 'comes', 'have', 'personnel', 'york', 'tuesday', 'is', 'tolls', 'temporarily', 'buses', 'cut', 'authority', 'with', 'city', 'decision', 'network', 'weekday', 'drops', 'system', 'three', 'new', 'budget', 'shortages', 'million', 'of', 'riders', 'which', 'service', 'to', 'transportation', 'ridership', 'on', 'and', 'the']
Topic 1:  ['the', 'and', 'transportation', 'on', 'ridership', 'to', 'service', 'million', 'network', 'in', 'riders

## Question 7

In [15]:
!pip install python-Levenshtein

In [16]:
from Levenshtein import distance as lev

In [17]:
lev('Kobe', 'Covid')

4

In [18]:
import numpy

In [19]:
def printDistances(distances, token1Length, token2Length):
    for t1 in range(token1Length + 1):
        for t2 in range(token2Length + 1):
            print(int(distances[t1][t2]), end=" ")
        print()

In [20]:
def levenshteinDistanceDP(token1, token2):
    distances = numpy.zeros((len(token1) + 1, len(token2) + 1))

    for t1 in range(len(token1) + 1):
        distances[t1][0] = t1

    for t2 in range(len(token2) + 1):
        distances[0][t2] = t2
        
    a = 0
    b = 0
    c = 0
    
    for t1 in range(1, len(token1) + 1):
        for t2 in range(1, len(token2) + 1):
            if (token1[t1-1] == token2[t2-1]):
                distances[t1][t2] = distances[t1 - 1][t2 - 1]
            else:
                a = distances[t1][t2 - 1]
                b = distances[t1 - 1][t2]
                c = distances[t1 - 1][t2 - 1]
                
                if (a <= b and a <= c):
                    distances[t1][t2] = a + 1
                elif (b <= a and b <= c):
                    distances[t1][t2] = b + 1
                else:
                    distances[t1][t2] = c + 1

    printDistances(distances, len(token1), len(token2))
    return distances[len(token1)][len(token2)]

In [21]:
levenshteinDistanceDP('Kobe','Covid')

0 1 2 3 4 5 
1 1 2 3 4 5 
2 2 1 2 3 4 
3 3 2 2 3 4 
4 4 3 3 3 4 


4.0

In [1]:
print(0.00104 > 0.00066)

True
